### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hasanalizxc** [Shaxzy/CS1.6-Multihack#1]
Hi there,

Hope you are fine. I have some opinions about this cheat. If you interest please write me.

Thank you so much for this and have a good day.

**Comment by Shaxzy** [comment]
I did not make this cheat. I found it on a russian forum and decided to share it here w/o credits to the proper owners. I can link you the main post if you’d like to?

**Comment by hasanalizxc** [comment]
No my friend i don't want to it, it is not problem, i just asked.

I have many opinions about this. I just have ideas because i don't have knowledge about programming like you. Do you interest?

EDIT2: Can you upload releases? I can't build it because of my pc is too old.

**Comment by imgladnotu** [comment]
i have compiled this and if you want the dll, pm me on discord im @GLaDOS#5736, id be happy to send it over

**Comment by Shaxzy** [comment]
Let me know if everything works. It’s maybe outdated idk

**Comment by imgladnotu** [comment]
actually it works, even on non-steam (pirated) version, though users will find more success using something else than the WaRzOnE version, that version is a bitch to load anything on and only few cheats actually work, also ive been using Extreme Injector 3.7.2 and even works with Xenos 2.3.2

**Comment by imgladnotu** [comment]
also it would be nice if you'd release this on unknowncheats.me

**Comment by Shaxzy** [comment]
> also it would be nice if you'd release this on unknowncheats.me

Banned from UC sadly

**Comment by Shaxzy** [comment]
> No my friend i don't want to it, it is not problem, i just asked.
> 
> I have many opinions about this. I just have ideas because i don't have knowledge about programming like you. Do you interest?
> 
> EDIT2: Can you upload releases? I can't build it because of my pc is too old.

Compiled it and added it to release here: https://github.com/Shaxzy/CS1.6-Multihack/releases/tag/v1.0
Also cleaned the code a little.

**Comment by Shaxzy** [comment]
> also it would be nice if you'd release this on unknowncheats.me

Sorry for the tag again, you can upload it to unknowncheats if you want to aslong as you give me credits^^
